apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prom-pvc-2
  labels:
    name: prometheus
spec:  
  storageClassName: manual  
  accessModes:
   - ReadWriteOnce
  resources:
    requests:   
      storage: 6Gi
