apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /tmp/k8s-persistent-data
  nodeSelector:
    kubernetes.io/hostname: kube8
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube8
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
    type: local
spec:
  storageClassName: manual 
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/k8s-persistent-data"
