apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prom-pvc-2
  labels:
    name: prometheus
spec:  
  storageClassName: local-storage  
  accessModes:
   - ReadWriteMany
  resources:
    requests:   
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prom-pvc-2
  labels:
    name: prometheus
spec:  
  storageClassName: manual
  accessModes:
   - ReadWriteMany
  resources:
    requests:   
      storage: 3Gi
