apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  labels:
  type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/home/kube8/k8s/persistent-data"
