apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prom-pvc
  labels:
    name: prometheus
spec:  
  storageClassName: manual  
  accessModes:
   - ReadWriteOnce
  resources:
    requests:   
      storage: 6Gi
---
# NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.7.42
    path: "/data1"
