apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-server-p
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-server-p
subjects:
  - kind: ServiceAccount
    name: prometheus-server-p
