# NFS
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc-2
  labels:
    name: prometheus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "nfs-storage-class"
  resources:
    requests:
      storage: 8Gi
