# NFS
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prom-pvc-2
#   labels:
#     name: prometheus
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: "nfs-storage-class"
#   resources:
#     requests:
#       storage: 8Gi

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  labels:
     name: prometheus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3000Gi
