apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prom-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: prometheus-server-p
    # Reference to upper's `metadata.namespace`
    namespace: knative-monitoring
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
